<a href="https://colab.research.google.com/github/SanthoshNagaraj94/Assignment_1_Numpy_santhosh/blob/main/Assignment_1_Numpy_santhosh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
np.__version__

'1.19.5'

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
x=np.zeros(10,int)
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [5]:
x.itemsize

8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [6]:
np.info(np.add)


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

method-1

In [7]:
x=np.zeros(10, int)
x[4]=1
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

method-2

In [8]:
y=np.arange(10)*0
y[4]=1
y

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [9]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [10]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [11]:
c=np.arange(0,9)
c.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [12]:
x=np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

method-1

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

method-2

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [15]:
x=np.random.random(27)
x.reshape(3,3,3)

array([[[0.69881107, 0.73329593, 0.99495826],
        [0.64079214, 0.1274964 , 0.90845681],
        [0.26794692, 0.23730953, 0.24938685]],

       [[0.66212304, 0.79876453, 0.15977721],
        [0.78261251, 0.10260515, 0.22632578],
        [0.26956917, 0.35138564, 0.00906208]],

       [[0.74655225, 0.43448365, 0.59502555],
        [0.11376859, 0.34700863, 0.64828058],
        [0.37432852, 0.0153703 , 0.48043425]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [16]:
a=np.random.random(100)
a.reshape(10,10)


array([[0.30955624, 0.91436041, 0.43386854, 0.4348936 , 0.78879132,
        0.95956291, 0.44717004, 0.74503319, 0.24188269, 0.79867265],
       [0.46009332, 0.55726979, 0.04765438, 0.71503498, 0.16522128,
        0.92828959, 0.89159083, 0.94469168, 0.41631822, 0.32054525],
       [0.05656581, 0.29432449, 0.52131899, 0.40688578, 0.53794047,
        0.1263415 , 0.05204243, 0.25894779, 0.97185151, 0.46108966],
       [0.74934146, 0.80796525, 0.19360013, 0.57239705, 0.05422971,
        0.91244328, 0.82609767, 0.2045578 , 0.36312357, 0.35922636],
       [0.395482  , 0.92483788, 0.61727709, 0.81768193, 0.12040064,
        0.01040013, 0.1521669 , 0.08144097, 0.26394448, 0.284269  ],
       [0.58962002, 0.62750359, 0.01907382, 0.72884592, 0.72909293,
        0.92264351, 0.46885611, 0.14356482, 0.72563128, 0.78431119],
       [0.6744697 , 0.38640528, 0.55121897, 0.27065398, 0.58328146,
        0.84625437, 0.61760266, 0.78848717, 0.02874598, 0.47752424],
       [0.21665667, 0.59213578, 0.0109525

In [17]:
a.min()

0.010400132069884993

In [18]:
a.max()

0.9966035200737038

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [19]:
a=np.random.random(30)
a

array([0.60059563, 0.60199352, 0.26658229, 0.41389576, 0.76848064,
       0.89565249, 0.77257342, 0.64396855, 0.1278969 , 0.2725682 ,
       0.08244866, 0.13070015, 0.61764637, 0.08011032, 0.15908224,
       0.41355058, 0.87672253, 0.99972254, 0.67697027, 0.94866493,
       0.45384236, 0.31740582, 0.78623044, 0.80132422, 0.26688236,
       0.6796143 , 0.68669079, 0.87360408, 0.42376894, 0.91805447])

In [20]:
a.mean()

0.5519081263702229

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [21]:
a=np.ones(10,int)
a[1:-1]=0
a

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [22]:
a=np.zeros(11,int)
a = np.pad(a, pad_width=1, mode='constant', constant_values=1)
a

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [23]:
a=np.zeros(9,int)
x=a.reshape(3,3)
x = np.pad(x, pad_width=1, mode='constant', constant_values=1)
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [24]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [25]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
a = np.diag(1+np.arange(4), k = -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [27]:
x = np.zeros ((8,8),int)
x[::2, 1::2] = 1
x[1::2, ::2]= 1

x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [28]:
x=np.unravel_index(100,(6,7,8))
x

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [29]:
ar= np.array([[0,1], [1,0]])
x = np.tile(ar,(4,4))
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [30]:
x=np.random.random((5,5))
x

array([[0.92049917, 0.96467478, 0.86811828, 0.4337592 , 0.62314056],
       [0.52142033, 0.17779038, 0.82152479, 0.8617824 , 0.42709605],
       [0.16135961, 0.23615829, 0.69393435, 0.31205773, 0.7123577 ],
       [0.40286554, 0.29906442, 0.26867388, 0.38745048, 0.37880276],
       [0.25264775, 0.14698846, 0.81930872, 0.30494895, 0.87581715]])

 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [31]:
color = np.dtype([("R", np.ubyte, 1),
                  ("G", np.ubyte, 1),
                  ("B", np.ubyte, 1),
                  ("A", np.ubyte, 1)])
color

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [32]:
a=np.arange(0,15)
a=a.reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [33]:
b=np.arange(0,6)
b=b.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

using np.dot method

In [34]:
z=np.dot(a,b)
z

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

using @ method

In [35]:
y=(a@b)
y

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [36]:
x=np.arange(0,12)
x[(x>3)&(x<8)]*=-1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [37]:
x=sum(range(5),-1)
x

9

In [38]:
from numpy import *
x=sum(range(5),-1)
x

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [39]:
Z=np.arange(10)

these expressions are legal except(Z<*Z*>Z)

In [40]:
Z**Z



array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [41]:
2 << Z >> 2


array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])

In [42]:
Z <- Z


array([False, False, False, False, False, False, False, False, False,
       False])

In [43]:
1j*Z


array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [44]:
Z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [45]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [46]:
x=np.random.uniform(-5,5,10)
x

array([-1.41362425,  0.38888379,  0.72200666,  2.15552014,  3.88487168,
       -3.99000014, -0.98789385, -0.16078912,  3.72790663,  0.09564722])

In [47]:
y=np.ceil(x)
y

array([-1.,  1.,  1.,  3.,  4., -3., -0., -0.,  4.,  1.])

In [48]:
z=np.abs(x)
z

array([1.41362425, 0.38888379, 0.72200666, 2.15552014, 3.88487168,
       3.99000014, 0.98789385, 0.16078912, 3.72790663, 0.09564722])

In [49]:
round=np.copysign(np.ceil(np.abs(x)), x)
round

array([-2.,  1.,  1.,  3.,  4., -4., -1., -1.,  4.,  1.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [50]:
a=np.random.randint(0,10,5)
b=np.random.randint(0,10,5)
a,b

(array([6, 4, 9, 8, 7]), array([6, 6, 3, 3, 7]))

In [51]:
c=intersect1d(a,b)
c

array([6, 7])

31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [52]:
np.seterr(all='ignore')

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

In [53]:
np.errstate(invalid='raise')

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [54]:
np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

TODAY

In [55]:
today=np.datetime64('today')
print(today)

2021-09-23


TOMORROW

In [56]:
tomorrow=np.datetime64('today')+np.timedelta64(1)
print(tomorrow)

2021-09-24


YESTERDAY

In [57]:
yesterday=np.datetime64('today')-np.timedelta64(1)
print(yesterday)

2021-09-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [58]:
JULY=np.arange('2016-07', '2016-08', dtype='datetime64[D]')
JULY

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [59]:
A=np.array([1,1,1])
B=np.array([2,2,2])
A

array([1, 1, 1])

In [60]:
B

array([2, 2, 2])

In [61]:
result=np.multiply((np.add(A,B)),(np.divide(np.negative(A),2)))
result

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [62]:
x=np.random.uniform(0,10,10)

In [63]:
x-x%1

array([0., 5., 4., 1., 5., 8., 2., 3., 3., 1.])

In [64]:
np.floor(x)

array([0., 5., 4., 1., 5., 8., 2., 3., 3., 1.])

In [65]:
np.ceil(x)

array([1., 6., 5., 2., 6., 9., 3., 4., 4., 2.])

In [66]:
x.astype(int)

array([0, 5, 4, 1, 5, 8, 2, 3, 3, 1])

In [67]:
np.trunc(x)

array([0., 5., 4., 1., 5., 8., 2., 3., 3., 1.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [68]:
x=np.zeros((5,5))
x=x+np.arange(0,5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [69]:
def Generator():
  for x in range(10):
    yield x

x=np.fromiter(Generator(),int)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [70]:
x=np.linspace(0,1,11 ,endpoint=False)
x[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [71]:
x=np.random.randint(0,10,10)
x

array([1, 4, 1, 1, 1, 7, 5, 7, 2, 3])

In [72]:
x=np.sort(x)
x

array([1, 1, 1, 1, 2, 3, 4, 5, 7, 7])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [73]:
x=np.random.uniform(0,10,10)
x

array([3.84655588, 1.58105173, 6.39176893, 0.88290884, 2.41001567,
       5.65722841, 1.04586276, 4.32660233, 1.15921041, 6.44702173])

In [74]:
np.sum(x)

33.74822667477123

In [75]:
np.add.reduce(x)

33.74822667477123

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [76]:
A=np.random.random(10)
B=np.random.random(10)

In [77]:
A,B

(array([0.41550442, 0.89633655, 0.93106942, 0.66387898, 0.27742799,
        0.57054528, 0.72436287, 0.3915669 , 0.46854021, 0.16670873]),
 array([0.65650287, 0.8885266 , 0.0268072 , 0.23851817, 0.18693108,
        0.59165966, 0.54035492, 0.09278976, 0.59839987, 0.18343201]))

In [78]:
np.allclose(A,B)

False

In [79]:
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [80]:
x=np.random.random(10)
x.flags.writeable=False
x

array([0.38518572, 0.71404019, 0.00593062, 0.38323868, 0.16636353,
       0.31084667, 0.98678138, 0.48462273, 0.1639102 , 0.59956016])

In [81]:
x[3]

0.3832386811410484

In [82]:
x[3]=5

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [83]:
a=np.random.random((10,2))
a

array([[0.80180374, 0.88185533],
       [0.55330145, 0.94000344],
       [0.07137163, 0.20391631],
       [0.16565022, 0.7035721 ],
       [0.30618644, 0.23649703],
       [0.78819388, 0.25197582],
       [0.28761352, 0.57429465],
       [0.81118755, 0.03123229],
       [0.80547389, 0.91302595],
       [0.65730417, 0.52570156]])

In [84]:
X,Y = a[:,0], a[:,1]
pol = np.sqrt(X**2+Y**2)
print(pol)


[1.19187166 1.09075614 0.21604576 0.72280959 0.38688626 0.82749103
 0.64228956 0.81178857 1.21754038 0.8416715 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [85]:
 x=np.arange(0,10)
 x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
 np.argmax(x)

9

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [87]:
x = np.zeros((3,3), [('x',float),('y',float)])
x['x'], x['y'] = np.meshgrid(np.linspace(0,1,3),
                             np.linspace(0,1,3))
x

array([[(0. , 0. ), (0.5, 0. ), (1. , 0. )],
       [(0. , 0.5), (0.5, 0.5), (1. , 0.5)],
       [(0. , 1. ), (0.5, 1. ), (1. , 1. )]],
      dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [88]:
X=np.array([1,2,3,4])
Y=np.array([2,3,4,5])
c=1/np.subtract.outer(X,Y)
c

array([[-1.        , -0.5       , -0.33333333, -0.25      ],
       [        inf, -1.        , -0.5       , -0.33333333],
       [ 1.        ,         inf, -1.        , -0.5       ],
       [ 0.5       ,  1.        ,         inf, -1.        ]])

In [89]:
np.linalg.det(c)

inf

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [90]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [91]:

x = np.zeros((16,16))
x


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [92]:
a = np.arange(100)
b = np.random.uniform(0,100)
index = (np.abs(a-b)).argmin()
print(a[index])

69


#### 51. Create a structured array representing a position (x,y) and a color (r,



g,b) (★★☆) 
(**hint**: dtype)

In [93]:
colour_rep = np.zeros(10, [ ('POS', [ ('X', float, 1),('Y', float, 1)]),
                            ('CLR',    [ ('R', float, 1),('G', float, 1),('B', float, 1)])])
colour_rep

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('POS', [('X', '<f8'), ('Y', '<f8')]), ('CLR', [('R', '<f8'), ('G', '<f8'), ('B', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [94]:
print("NORMAL METHOD ")
print(" ")
A = np.random.random((10,2))
X,Y = np.atleast_2d(A[:,0], A[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
print(" ")


print("USING SKLEARN METHOD ")
print(" ")
import scipy.spatial
D = scipy.spatial.distance.cdist(A,A)
print(D)

NORMAL METHOD 
 
[[0.         0.51981514 0.10933541 0.81865314 0.95370888 0.81187002
  0.67769707 0.79211086 0.5236035  0.72175211]
 [0.51981514 0.         0.41520577 0.65854563 0.67487853 0.92696461
  0.77504418 0.32578977 0.3705561  0.70794309]
 [0.10933541 0.41520577 0.         0.78523141 0.90077387 0.83833886
  0.69492196 0.7007476  0.47242312 0.71540291]
 [0.81865314 0.65854563 0.78523141 0.         0.20939429 0.44642427
  0.3636243  0.5175415  0.32458133 0.20865601]
 [0.95370888 0.67487853 0.90077387 0.20939429 0.         0.6487696
  0.57301495 0.43744158 0.43048675 0.41804759]
 [0.81187002 0.92696461 0.83833886 0.44642427 0.6487696  0.
  0.15354989 0.91111766 0.56389063 0.25551104]
 [0.67769707 0.77504418 0.69492196 0.3636243  0.57301495 0.15354989
  0.         0.77892702 0.41613699 0.15502051]
 [0.79211086 0.32578977 0.7007476  0.5175415  0.43744158 0.91111766
  0.77892702 0.         0.39165061 0.65771886]
 [0.5236035  0.3705561  0.47242312 0.32458133 0.43048675 0.56389063
  0.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [95]:
X=(np.random.rand(30)*50).astype(float32)
X,X.dtype


(array([12.170144  , 42.834465  , 15.894835  , 17.934214  ,  8.035187  ,
        25.772331  , 21.200035  , 24.92928   ,  5.604413  , 30.681063  ,
        22.917122  ,  2.9483933 ,  0.5850905 ,  8.242385  ,  0.47457588,
        39.454388  , 19.8022    , 33.607403  , 23.564627  , 28.194681  ,
        48.452927  , 41.635525  , 14.460827  , 26.306452  , 10.315717  ,
        24.19441   , 24.580404  , 40.109276  , 13.324302  , 36.99484   ],
       dtype=float32), dtype('float32'))

In [96]:
X=X.astype(int32)

In [97]:
X

array([12, 42, 15, 17,  8, 25, 21, 24,  5, 30, 22,  2,  0,  8,  0, 39, 19,
       33, 23, 28, 48, 41, 14, 26, 10, 24, 24, 40, 13, 36], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [98]:
from io import StringIO

string = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11 ''')
x = np.genfromtxt(string, delimiter=",", dtype=np.int)
x

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [99]:
X = np.arange(9).reshape(3,3)
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
for i in np.ndenumerate(X):
  print(i)

((0, 0), 0)
((0, 1), 1)
((0, 2), 2)
((1, 0), 3)
((1, 1), 4)
((1, 2), 5)
((2, 0), 6)
((2, 1), 7)
((2, 2), 8)


In [101]:
for i in np.ndindex(X.shape):
  print(i,X[i])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [102]:
X, Y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 2.0, 0.5
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.90079884 0.95337615 0.96923323 0.95337615 0.90079884]
 [0.95337615 0.9946527  1.         0.9946527  0.95337615]
 [0.96923323 1.         0.96923323 1.         0.96923323]
 [0.95337615 0.9946527  1.         0.9946527  0.95337615]
 [0.90079884 0.95337615 0.96923323 0.95337615 0.90079884]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [103]:
n = 5
p = 5
x = np.zeros((n,n))
np.put(x, np.random.choice(range(n*n), p, ),2)
x

array([[0., 0., 0., 0., 0.],
       [2., 0., 2., 0., 2.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 2., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [104]:
X = np.random.rand(5, 10)
X

array([[0.61572157, 0.86040998, 0.0425217 , 0.83170023, 0.9587647 ,
        0.91330437, 0.17261172, 0.32272788, 0.91490408, 0.44775425],
       [0.54398702, 0.14199182, 0.34699888, 0.03210566, 0.34105601,
        0.2317417 , 0.23821614, 0.18382055, 0.93438342, 0.02585935],
       [0.93802166, 0.10513873, 0.16803487, 0.82809138, 0.68743152,
        0.09109362, 0.5640228 , 0.90593475, 0.43080457, 0.29708427],
       [0.18810795, 0.72717717, 0.3325116 , 0.23993172, 0.54633768,
        0.12599452, 0.97846665, 0.30239644, 0.23441713, 0.61572478],
       [0.79060336, 0.28980105, 0.71472846, 0.07550059, 0.85421763,
        0.03977496, 0.90274126, 0.61121253, 0.97334555, 0.51014801]])

In [105]:
Y = X - X.mean(axis=1, keepdims=True)

Y

array([[ 0.00767952,  0.25236793, -0.56552034,  0.22365818,  0.35072265,
         0.30526233, -0.43543033, -0.28531417,  0.30686203, -0.1602878 ],
       [ 0.24197096, -0.16002423,  0.04498282, -0.26991039,  0.03903995,
        -0.07027435, -0.06379991, -0.11819551,  0.63236737, -0.2761567 ],
       [ 0.43645584, -0.39642709, -0.33353095,  0.32652556,  0.1858657 ,
        -0.4104722 ,  0.06245699,  0.40436893, -0.07076124, -0.20448155],
       [-0.24099862,  0.29807061, -0.09659497, -0.18917484,  0.11723111,
        -0.30311204,  0.54936009, -0.12671012, -0.19468943,  0.18661821],
       [ 0.21439602, -0.28640629,  0.13852112, -0.50070675,  0.27801029,
        -0.53643238,  0.32653392,  0.03500519,  0.39713821, -0.06605933]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [106]:

x = np.random.randint(0,100,(3,3))
x



array([[69, 58, 30],
       [ 7,  8, 59],
       [63, 27, 71]])

In [107]:
print(x[x[:,0].argsort()])

[[ 7  8 59]
 [63 27 71]
 [69 58 30]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

USING NUMPY FUNCTION

In [108]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


In [109]:
Z

array([[2, 0, 2, 1, 0, 0, 1, 0, 0, 1],
       [0, 2, 1, 2, 2, 1, 2, 1, 0, 1],
       [0, 0, 2, 2, 0, 0, 2, 1, 0, 0]])

USING CONVENTIONAL METHOD

In [110]:
if 0 in Z:
  print(True)
else:
  print(False)


True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [111]:
X = np.random.uniform(0,10,100)
z = 5
N = X.flat[np.abs(X - z).argmin()]
print(N)

4.9866418259784275


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [112]:
a=np.arange(0,3).reshape(1,3)
b=np.arange(0,3).reshape(3,1)


In [113]:
a

array([[0, 1, 2]])

In [114]:
b

array([[0],
       [1],
       [2]])

In [115]:
summ=np.nditer([a,b,None])
for x,y,z in summ: z[...] = x + y
print(summ.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [116]:
a = np.arange(0,10).astype(int)
b = np.arange(0,10).astype(int)
a += np.bincount(b, minlength=len(a))
print(a)




[ 1  2  3  4  5  6  7  8  9 10]


In [117]:
np.add.at(a, b, 1)
print(a)

[ 2  3  4  5  6  7  8  9 10 11]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [118]:
a = [10,20,30,40,50,100]
b = [1,2,3,4,5,6]
c = np.bincount(b,a).astype(int32)
print(c)

[  0  10  20  30  40  50 100]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [119]:
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)
clrs = np.dot(I.astype(np.uint32),[1,256,2500])

count = len(np.unique(clrs))
print(count)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [120]:
a= np.random.randint(0,10,(4,4,4,4))

sum = a.sum(axis=(-2,-1))
sum

array([[86, 59, 77, 77],
       [72, 66, 67, 61],
       [88, 67, 86, 83],
       [88, 90, 74, 78]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [121]:
D = np.arange(0,100,20)
S = np.arange(0,100,20)
D_sums = np.bincount(S, weights=D)
D_sums

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0., 20.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., 40.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 60.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0., 80.])

In [122]:
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[ 0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan 20. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan 40. nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan 60. nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan 80.]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [123]:
A = np.random.uniform(0,10,(3,3))
B = np.random.uniform(0,10,(3,3))

In [124]:
A

array([[0.9126474 , 0.18286183, 1.94302579],
       [2.42547253, 6.03186412, 4.91637606],
       [1.52009739, 7.71133567, 0.99958742]])

In [125]:
B

array([[2.32442999, 8.61085807, 1.34029165],
       [3.69265355, 8.89376502, 3.62064212],
       [4.89511525, 5.28147091, 2.90167754]])

In [126]:
np.diag(np.dot(A, B))


array([ 12.30796554, 100.49707897,  32.85784093])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [127]:
a=[1,2,3,4,5]
zero=3
x=np.zeros(len(a)+(len(a)-1)*zero)
x[::zero+1]=a
print(x)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [129]:
A=np.ones((5,5,3))
A

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [130]:
B=np.ones((5,5))*5
B

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [131]:
C=A * B[:,:,None]
C

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [133]:
x = np.arange(49).reshape(7,7)
x[[0,1]] = x[[1,0]]
x

array([[ 7,  8,  9, 10, 11, 12, 13],
       [ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [134]:
A= np.bincount([2,5,6,7,9,8])
C = np.repeat(np.arange(len(A)), A)
C

array([2, 5, 6, 7, 8, 9])

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [138]:
a=[1,2,3,4,5]
print(np.cumsum(a).mean())

7.0


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [140]:
from numpy.lib import stride_tricks
def roll(a, w):
    shape = (a.size - w + 1, w)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = roll(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [146]:
a = np.random.randint(0,2,100)
np.logical_not(a, out=a).astype(float64)



array([1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
       1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1.])

In [147]:
np.negative(a, out=a).astype(float64)

array([-1., -1.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0., -1.,  0., -1.,
       -1.,  0.,  0.,  0., -1., -1., -1., -1.,  0., -1.,  0., -1.,  0.,
       -1.,  0.,  0., -1., -1., -1., -1.,  0., -1.,  0., -1.,  0.,  0.,
        0.,  0.,  0., -1.,  0., -1., -1.,  0., -1., -1., -1., -1., -1.,
       -1., -1.,  0., -1., -1., -1.,  0.,  0., -1.,  0.,  0., -1., -1.,
       -1.,  0., -1.,  0.,  0.,  0.,  0., -1.,  0.,  0., -1.,  0.,  0.,
        0., -1.,  0., -1.,  0.,  0., -1.,  0.,  0., -1.,  0., -1.,  0.,
        0., -1., -1.,  0., -1., -1.,  0.,  0., -1.])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [151]:
arry = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14]).astype(uint32)
R = stride_tricks.as_strided(arry,(11,4),(4,4))
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [155]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
rank

10

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [162]:
a = np.random.randint(0,100,10)
np.bincount(a).argmax()

0

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [163]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
C

array([[[[0, 0, 1],
         [1, 4, 3],
         [1, 2, 4]],

        [[0, 1, 4],
         [4, 3, 0],
         [2, 4, 4]],

        [[1, 4, 0],
         [3, 0, 0],
         [4, 4, 2]],

        [[4, 0, 0],
         [0, 0, 4],
         [4, 2, 3]],

        [[0, 0, 2],
         [0, 4, 0],
         [2, 3, 2]],

        [[0, 2, 0],
         [4, 0, 4],
         [3, 2, 1]],

        [[2, 0, 0],
         [0, 4, 4],
         [2, 1, 0]],

        [[0, 0, 2],
         [4, 4, 4],
         [1, 0, 1]]],


       [[[1, 4, 3],
         [1, 2, 4],
         [2, 0, 3]],

        [[4, 3, 0],
         [2, 4, 4],
         [0, 3, 1]],

        [[3, 0, 0],
         [4, 4, 2],
         [3, 1, 1]],

        [[0, 0, 4],
         [4, 2, 3],
         [1, 1, 2]],

        [[0, 4, 0],
         [2, 3, 2],
         [1, 2, 0]],

        [[4, 0, 4],
         [3, 2, 1],
         [2, 0, 0]],

        [[0, 4, 4],
         [2, 1, 0],
         [0, 0, 2]],

        [[4, 4, 4],
         [1, 0, 1],
         [0, 2, 1]]],


    

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [165]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
S

Symetric([[ 1, 13,  9,  8, 11],
          [13,  1,  2,  5,  6],
          [ 9,  2,  2, 42,  6],
          [ 8,  5, 42,  1,  1],
          [11,  6,  6,  1,  6]])

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [166]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
S

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [170]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [175]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 8

print (Z[np.argsort(Z)[-n:]])


[9992 9993 9994 9995 9996 9997 9998 9999]


In [176]:

print (Z[np.argpartition(-Z,n)[:n]])

[9999 9998 9997 9996 9995 9994 9992 9993]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)