<a href="https://colab.research.google.com/github/SanthoshNagaraj94/Assignment_1_Numpy_santhosh/blob/main/Assignment_1_Numpy_santhosh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'1.19.5'

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x=np.zeros(10,int)
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x.itemsize

8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

method-1

In [ ]:
x=np.zeros(10, int)
x[4]=1
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

method-2

In [ ]:
y=np.arange(10)*0
y[4]=1
y

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
c=np.arange(0,9)
c.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x=np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

method-1

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

method-2

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x=np.random.random(27)
x.reshape(3,3,3)

array([[[0.63042201, 0.0372262 , 0.24643121],
        [0.24267289, 0.70969152, 0.04793516],
        [0.84133913, 0.08408454, 0.80288105]],

       [[0.97777156, 0.61167854, 0.87940193],
        [0.86815079, 0.62644934, 0.08391923],
        [0.07524054, 0.9957538 , 0.44577667]],

       [[0.76824934, 0.68579314, 0.84700135],
        [0.11948741, 0.97526024, 0.79833839],
        [0.58772108, 0.49511954, 0.26367544]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
a=np.random.random(100)
a.reshape(10,10)


array([[0.37032516, 0.86407239, 0.86960939, 0.25763427, 0.60807155,
        0.78691062, 0.62171151, 0.08883051, 0.17729021, 0.0346565 ],
       [0.00303628, 0.45565011, 0.50539239, 0.66818358, 0.13799712,
        0.85915529, 0.15504619, 0.54927698, 0.53455111, 0.20267016],
       [0.59439821, 0.33217254, 0.34829292, 0.48088768, 0.40072314,
        0.82224102, 0.8238538 , 0.13883785, 0.33952346, 0.8843617 ],
       [0.13531441, 0.11886083, 0.48925951, 0.41291572, 0.89129573,
        0.38649624, 0.15796351, 0.42225462, 0.31882755, 0.49679969],
       [0.55220361, 0.61360301, 0.53834166, 0.47671867, 0.67907682,
        0.70607839, 0.47692189, 0.62757688, 0.73844338, 0.4055678 ],
       [0.41808599, 0.60883045, 0.61969593, 0.3597694 , 0.66560427,
        0.52859001, 0.74983336, 0.51493766, 0.48270936, 0.97627501],
       [0.98720015, 0.76363258, 0.08880977, 0.88449505, 0.47073374,
        0.59557804, 0.5506887 , 0.67429477, 0.42079413, 0.98284515],
       [0.44995615, 0.85568092, 0.8379871

In [ ]:
a.min()

0.0030362845464684263

In [ ]:
a.max()

0.9958653110905392

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
a=np.random.random(30)
a

array([0.04264376, 0.79845565, 0.40616191, 0.26842986, 0.35734787,
       0.85074147, 0.02833974, 0.23275274, 0.69585277, 0.74590173,
       0.08713063, 0.38050914, 0.38953948, 0.89872795, 0.48075794,
       0.26107626, 0.14969885, 0.88444788, 0.17707457, 0.21512229,
       0.31049229, 0.1193231 , 0.06806455, 0.69954239, 0.46682274,
       0.98548411, 0.52683942, 0.19547047, 0.0081527 , 0.21121369])

In [ ]:
a.mean()

0.398070598975482

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
a=np.ones(10,int)
a[1:-1]=0
a

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
a=np.zeros(11,int)
a = np.pad(a, pad_width=1, mode='constant', constant_values=1)
a

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
a=np.zeros(9,int)
x=a.reshape(3,3)
x = np.pad(x, pad_width=1, mode='constant', constant_values=1)
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
a = np.diag(1+np.arange(4), k = -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.zeros ((8,8),int)
x[::2, 1::2] = 1
x[1::2, ::2]= 1

x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
x=np.unravel_index(100,(6,7,8))
x

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
ar= np.array([[0,1], [1,0]])
x = np.tile(ar,(4,4))
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x=np.random.random((5,5))
x

array([[0.04313544, 0.09666125, 0.55690496, 0.67152307, 0.51727487],
       [0.52319093, 0.89877574, 0.63047627, 0.29255214, 0.43375269],
       [0.75602409, 0.49006648, 0.67735172, 0.28129819, 0.89130086],
       [0.24957446, 0.85095272, 0.91904357, 0.89568585, 0.19179521],
       [0.25902477, 0.47087195, 0.4096473 , 0.19240887, 0.02794386]])

 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("R", np.ubyte, 1),
                  ("G", np.ubyte, 1),
                  ("B", np.ubyte, 1),
                  ("A", np.ubyte, 1)])
color

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a=np.arange(0,15)
a=a.reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
b=np.arange(0,6)
b=b.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

using np.dot method

In [ ]:
z=np.dot(a,b)
z

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

using @ method

In [ ]:
y=(a@b)
y

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x=np.arange(0,12)
x[(x>3)&(x<8)]*=-1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
x=sum(range(5),-1)
x

9

In [ ]:
from numpy import *
x=sum(range(5),-1)
x

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=np.arange(10)

these expressions are legal except(Z<*Z*>Z)

In [ ]:
Z**Z



array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [ ]:
2 << Z >> 2


array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])

In [ ]:
Z <- Z


array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
1j*Z


array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [ ]:
Z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x=np.random.uniform(-5,5,10)
x

array([-0.86005131,  2.37852848, -2.99954696, -4.08142409,  3.3890676 ,
       -3.72725788,  2.99200495,  3.8149815 ,  4.94232653,  4.79721968])

In [ ]:
y=np.ceil(x)
y

array([-0.,  3., -2., -4.,  4., -3.,  3.,  4.,  5.,  5.])

In [ ]:
z=np.abs(x)
z

array([0.86005131, 2.37852848, 2.99954696, 4.08142409, 3.3890676 ,
       3.72725788, 2.99200495, 3.8149815 , 4.94232653, 4.79721968])

In [ ]:
round=np.copysign(np.ceil(np.abs(x)), x)
round

array([-1.,  3., -3., -5.,  4., -4.,  3.,  4.,  5.,  5.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a=np.random.randint(0,10,5)
b=np.random.randint(0,10,5)
a,b

(array([0, 5, 2, 9, 3]), array([5, 7, 5, 9, 7]))

In [ ]:
c=intersect1d(a,b)
c

array([5, 9])

31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all='ignore')

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

In [ ]:
np.errstate(invalid='raise')

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

TODAY

In [ ]:
today=np.datetime64('today')
print(today)

2021-09-21


TOMORROW

In [ ]:
tomorrow=np.datetime64('today')+np.timedelta64(1)
print(tomorrow)

2021-09-22


YESTERDAY

In [ ]:
yesterday=np.datetime64('today')-np.timedelta64(1)
print(yesterday)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
JULY=np.arange('2016-07', '2016-08', dtype='datetime64[D]')
JULY

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A=np.array([1,1,1])
B=np.array([2,2,2])
A

array([1, 1, 1])

In [ ]:
B

array([2, 2, 2])

In [ ]:
result=np.multiply((np.add(A,B)),(np.divide(np.negative(A),2)))
result

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x=np.random.uniform(0,10,10)

In [ ]:
x-x%1

array([0., 5., 9., 8., 9., 1., 7., 0., 9., 3.])

In [ ]:
np.floor(x)

array([0., 5., 9., 8., 9., 1., 7., 0., 9., 3.])

In [ ]:
np.ceil(x)

array([ 1.,  6., 10.,  9., 10.,  2.,  8.,  1., 10.,  4.])

In [ ]:
x.astype(int)

array([0, 5, 9, 8, 9, 1, 7, 0, 9, 3])

In [ ]:
np.trunc(x)

array([0., 5., 9., 8., 9., 1., 7., 0., 9., 3.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x=np.zeros((5,5))
x=x+np.arange(0,5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def Generator():
  for x in range(10):
    yield x

x=np.fromiter(Generator(),int)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x=np.linspace(0,1,11 ,endpoint=False)
x[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x=np.random.randint(0,10,10)
x

array([6, 1, 5, 0, 2, 9, 6, 2, 4, 9])

In [ ]:
x=np.sort(x)
x

array([0, 1, 2, 2, 4, 5, 6, 6, 9, 9])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x=np.random.uniform(0,10,10)
x

array([6.10303807, 9.90355442, 5.01947873, 6.09285241, 6.62214205,
       4.08701291, 6.76431562, 1.87204913, 5.28723156, 6.37267697])

In [ ]:
np.sum(x)

58.12435185981312

In [ ]:
np.add.reduce(x)

58.12435185981312

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A=np.random.random(10)
B=np.random.random(10)

In [ ]:
A,B

(array([0.75978243, 0.53445045, 0.23293834, 0.5454122 , 0.55517458,
        0.6602202 , 0.00414131, 0.44783032, 0.29199079, 0.1356814 ]),
 array([0.34465181, 0.95021307, 0.40841991, 0.16778563, 0.72506277,
        0.91102581, 0.39967713, 0.18121989, 0.74657898, 0.17411251]))

In [ ]:
np.allclose(A,B)

False

In [ ]:
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
x=np.random.random(10)
x.flags.writeable=False
x

array([0.52147106, 0.95843474, 0.41927277, 0.74101703, 0.88431936,
       0.70978679, 0.23367704, 0.65195276, 0.77273747, 0.98187257])

In [ ]:
x[3]

0.7410170254089943

In [ ]:
x[3]=5

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
a=np.random.random((10,2))
a

array([[0.51286687, 0.33375232],
       [0.20141823, 0.76503806],
       [0.49916736, 0.10292862],
       [0.85136818, 0.16593467],
       [0.49826639, 0.86046649],
       [0.71991669, 0.01274113],
       [0.50733365, 0.75826178],
       [0.92547468, 0.60403227],
       [0.12723762, 0.85099201],
       [0.75483206, 0.34701445]])

In [ ]:
X,Y = a[:,0], a[:,1]
pol = np.sqrt(X**2+Y**2)
print(pol)


[0.61190116 0.79110842 0.50966887 0.86738808 0.99431986 0.72002943
 0.91233128 1.10515083 0.86045152 0.83077702]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
 x=np.arange(0,10)
 x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
 np.argmax(x)

9

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
x = np.zeros((3,3), [('x',float),('y',float)])
x['x'], x['y'] = np.meshgrid(np.linspace(0,1,3),
                             np.linspace(0,1,3))
x

array([[(0. , 0. ), (0.5, 0. ), (1. , 0. )],
       [(0. , 0.5), (0.5, 0.5), (1. , 0.5)],
       [(0. , 1. ), (0.5, 1. ), (1. , 1. )]],
      dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X=np.array([1,2,3,4])
Y=np.array([2,3,4,5])
c=1/np.subtract.outer(X,Y)
c

array([[-1.        , -0.5       , -0.33333333, -0.25      ],
       [        inf, -1.        , -0.5       , -0.33333333],
       [ 1.        ,         inf, -1.        , -0.5       ],
       [ 0.5       ,  1.        ,         inf, -1.        ]])

In [ ]:
np.linalg.det(c)

inf

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:

x = np.zeros((16,16))
x


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
a = np.arange(100)
b = np.random.uniform(0,100)
index = (np.abs(a-b)).argmin()
print(a[index])

32


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)